server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/musicrecommend?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.example.music_recommend_system.entity